// <auto-generated />
namespace EF6Basic.Migrations.KabulDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AgeToBirthday : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AgeToBirthday));
        
        string IMigrationMetadata.Id
        {
            get { return "202303041558415_AgeToBirthday"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
